name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Check semver
        run: |
          cargo install cargo-semver-checks --locked
          cargo semver-checks check-release

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Login to Crates.io
        run: cargo login ${{ secrets.CRATESIO_TOKEN }}

      - name: Publish
        run: cargo release publish --execute --no-confirm --allow-branch HEAD

      - name: GitHub Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          body: Check the [Changelog](https://github.com/resend/resend-rust/blob/main/CHANGELOG.md)
